//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SoftCobEntities : DbContext
    {
        public SoftCobEntities()
            : base("name=SoftCobEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SoftCob_DEPARTAMENTO> SoftCob_DEPARTAMENTO { get; set; }
        public virtual DbSet<SoftCob_MENU> SoftCob_MENU { get; set; }
        public virtual DbSet<SoftCob_MENU_TAREA> SoftCob_MENU_TAREA { get; set; }
        public virtual DbSet<SoftCob_PERFIL> SoftCob_PERFIL { get; set; }
        public virtual DbSet<SoftCob_PERFIL_MENU_TAREA> SoftCob_PERFIL_MENU_TAREA { get; set; }
        public virtual DbSet<SoftCob_TAREA> SoftCob_TAREA { get; set; }
        public virtual DbSet<SoftCob_USUARIO> SoftCob_USUARIO { get; set; }
        public virtual DbSet<SoftCob_GESTOR_SUPERVISOR> SoftCob_GESTOR_SUPERVISOR { get; set; }
        public virtual DbSet<SoftCob_LOGUEO_TIEMPOS> SoftCob_LOGUEO_TIEMPOS { get; set; }
        public virtual DbSet<SoftCob_CIUDAD> SoftCob_CIUDAD { get; set; }
        public virtual DbSet<SoftCob_PARAMETRO_CABECERA> SoftCob_PARAMETRO_CABECERA { get; set; }
        public virtual DbSet<SoftCob_PARAMETRO_DETALLE> SoftCob_PARAMETRO_DETALLE { get; set; }
        public virtual DbSet<SoftCob_PROVINCIA> SoftCob_PROVINCIA { get; set; }
        public virtual DbSet<SoftCob_CEDENTE> SoftCob_CEDENTE { get; set; }
        public virtual DbSet<SoftCob_PRODUCTOS_CEDENTE> SoftCob_PRODUCTOS_CEDENTE { get; set; }
        public virtual DbSet<SoftCob_CATALOGO_PRODUCTOS_CEDENTE> SoftCob_CATALOGO_PRODUCTOS_CEDENTE { get; set; }
        public virtual DbSet<SoftCob_ACCION> SoftCob_ACCION { get; set; }
        public virtual DbSet<SoftCob_CONTACTO> SoftCob_CONTACTO { get; set; }
        public virtual DbSet<SoftCob_EFECTO> SoftCob_EFECTO { get; set; }
        public virtual DbSet<SoftCob_RESPUESTA> SoftCob_RESPUESTA { get; set; }
        public virtual DbSet<SoftCob_SPEECH_CABECERA> SoftCob_SPEECH_CABECERA { get; set; }
        public virtual DbSet<SoftCob_SPEECH_DETALLE> SoftCob_SPEECH_DETALLE { get; set; }
        public virtual DbSet<SoftCob_CAMPOS_SPEECH> SoftCob_CAMPOS_SPEECH { get; set; }
        public virtual DbSet<SoftCob_REGISTRO_VOLVERALLAMAR> SoftCob_REGISTRO_VOLVERALLAMAR { get; set; }
        public virtual DbSet<SoftCob_TELEFONOS_CEDENTE> SoftCob_TELEFONOS_CEDENTE { get; set; }
        public virtual DbSet<SoftCob_BRENCH> SoftCob_BRENCH { get; set; }
        public virtual DbSet<SoftCob_LISTATRABAJO_ACTIVAS> SoftCob_LISTATRABAJO_ACTIVAS { get; set; }
        public virtual DbSet<SoftCob_LISTATRABAJO_CABECERA> SoftCob_LISTATRABAJO_CABECERA { get; set; }
        public virtual DbSet<SoftCob_LISTATRABAJO_DETALLE> SoftCob_LISTATRABAJO_DETALLE { get; set; }
    
        public virtual ObjectResult<string> FunMenuEditUpdate(string in_check, Nullable<int> in_codigomenu, Nullable<int> in_codigotarea, Nullable<int> in_emprcodigo, string in_auxv1, string in_auxv2, string in_auxv3, Nullable<int> in_auxi1, Nullable<int> in_auxi2, Nullable<int> in_auxi3, Nullable<int> in_usucodigo, string in_terminal)
        {
            var in_checkParameter = in_check != null ?
                new ObjectParameter("in_check", in_check) :
                new ObjectParameter("in_check", typeof(string));
    
            var in_codigomenuParameter = in_codigomenu.HasValue ?
                new ObjectParameter("in_codigomenu", in_codigomenu) :
                new ObjectParameter("in_codigomenu", typeof(int));
    
            var in_codigotareaParameter = in_codigotarea.HasValue ?
                new ObjectParameter("in_codigotarea", in_codigotarea) :
                new ObjectParameter("in_codigotarea", typeof(int));
    
            var in_emprcodigoParameter = in_emprcodigo.HasValue ?
                new ObjectParameter("in_emprcodigo", in_emprcodigo) :
                new ObjectParameter("in_emprcodigo", typeof(int));
    
            var in_auxv1Parameter = in_auxv1 != null ?
                new ObjectParameter("in_auxv1", in_auxv1) :
                new ObjectParameter("in_auxv1", typeof(string));
    
            var in_auxv2Parameter = in_auxv2 != null ?
                new ObjectParameter("in_auxv2", in_auxv2) :
                new ObjectParameter("in_auxv2", typeof(string));
    
            var in_auxv3Parameter = in_auxv3 != null ?
                new ObjectParameter("in_auxv3", in_auxv3) :
                new ObjectParameter("in_auxv3", typeof(string));
    
            var in_auxi1Parameter = in_auxi1.HasValue ?
                new ObjectParameter("in_auxi1", in_auxi1) :
                new ObjectParameter("in_auxi1", typeof(int));
    
            var in_auxi2Parameter = in_auxi2.HasValue ?
                new ObjectParameter("in_auxi2", in_auxi2) :
                new ObjectParameter("in_auxi2", typeof(int));
    
            var in_auxi3Parameter = in_auxi3.HasValue ?
                new ObjectParameter("in_auxi3", in_auxi3) :
                new ObjectParameter("in_auxi3", typeof(int));
    
            var in_usucodigoParameter = in_usucodigo.HasValue ?
                new ObjectParameter("in_usucodigo", in_usucodigo) :
                new ObjectParameter("in_usucodigo", typeof(int));
    
            var in_terminalParameter = in_terminal != null ?
                new ObjectParameter("in_terminal", in_terminal) :
                new ObjectParameter("in_terminal", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("FunMenuEditUpdate", in_checkParameter, in_codigomenuParameter, in_codigotareaParameter, in_emprcodigoParameter, in_auxv1Parameter, in_auxv2Parameter, in_auxv3Parameter, in_auxi1Parameter, in_auxi2Parameter, in_auxi3Parameter, in_usucodigoParameter, in_terminalParameter);
        }
    
        public virtual ObjectResult<string> FunUpdateParametroDetalle(Nullable<int> in_paracodigo, Nullable<int> in_padecodigo, string in_padenombre, string in_padevalorV, Nullable<int> in_padevalorI, Nullable<int> in_padeorden, Nullable<bool> in_padeestado)
        {
            var in_paracodigoParameter = in_paracodigo.HasValue ?
                new ObjectParameter("in_paracodigo", in_paracodigo) :
                new ObjectParameter("in_paracodigo", typeof(int));
    
            var in_padecodigoParameter = in_padecodigo.HasValue ?
                new ObjectParameter("in_padecodigo", in_padecodigo) :
                new ObjectParameter("in_padecodigo", typeof(int));
    
            var in_padenombreParameter = in_padenombre != null ?
                new ObjectParameter("in_padenombre", in_padenombre) :
                new ObjectParameter("in_padenombre", typeof(string));
    
            var in_padevalorVParameter = in_padevalorV != null ?
                new ObjectParameter("in_padevalorV", in_padevalorV) :
                new ObjectParameter("in_padevalorV", typeof(string));
    
            var in_padevalorIParameter = in_padevalorI.HasValue ?
                new ObjectParameter("in_padevalorI", in_padevalorI) :
                new ObjectParameter("in_padevalorI", typeof(int));
    
            var in_padeordenParameter = in_padeorden.HasValue ?
                new ObjectParameter("in_padeorden", in_padeorden) :
                new ObjectParameter("in_padeorden", typeof(int));
    
            var in_padeestadoParameter = in_padeestado.HasValue ?
                new ObjectParameter("in_padeestado", in_padeestado) :
                new ObjectParameter("in_padeestado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("FunUpdateParametroDetalle", in_paracodigoParameter, in_padecodigoParameter, in_padenombreParameter, in_padevalorVParameter, in_padevalorIParameter, in_padeordenParameter, in_padeestadoParameter);
        }
    }
}
