//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_CLIENTE_DEUDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_CLIENTE_DEUDOR()
        {
            this.SoftCob_CITACIONES_CAB = new HashSet<SoftCob_CITACIONES_CAB>();
            this.SoftCob_CUENTA_DEUDOR = new HashSet<SoftCob_CUENTA_DEUDOR>();
        }
    
        public int CLDE_CODIGO { get; set; }
        public int PERS_CODIGO { get; set; }
        public int CPCE_CODIGO { get; set; }
        public string clde_codigoagencia { get; set; }
        public bool clde_estado { get; set; }
        public string clde_auxv1 { get; set; }
        public string clde_auxv2 { get; set; }
        public string clde_auxv3 { get; set; }
        public Nullable<int> clde_auxi1 { get; set; }
        public Nullable<int> clde_auxi2 { get; set; }
        public Nullable<int> clde_auxi3 { get; set; }
        public System.DateTime clde_fechacreacion { get; set; }
        public int clde_usuariocreacion { get; set; }
        public string clde_terminalcreacion { get; set; }
        public System.DateTime clde_fum { get; set; }
        public int clde_uum { get; set; }
        public string clde_tum { get; set; }
    
        public virtual SoftCob_CATALOGO_PRODUCTOS_CEDENTE SoftCob_CATALOGO_PRODUCTOS_CEDENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_CITACIONES_CAB> SoftCob_CITACIONES_CAB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_CUENTA_DEUDOR> SoftCob_CUENTA_DEUDOR { get; set; }
        public virtual SoftCob_PERSONA SoftCob_PERSONA { get; set; }
    }
}
