//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_PROTOCOLO_EVALUACION
    {
        public int PREV_CODIGO { get; set; }
        public int prev_codprotocolo { get; set; }
        public int prev_codigopadre { get; set; }
        public string prev_descripcion { get; set; }
        public bool prev_estado { get; set; }
        public int prev_califica { get; set; }
        public string prev_nivel { get; set; }
        public int prev_orden { get; set; }
        public string prev_auxv1 { get; set; }
        public string prev_auxv2 { get; set; }
        public string prev_auxv3 { get; set; }
        public string prev_auxv4 { get; set; }
        public Nullable<int> prev_auxi1 { get; set; }
        public Nullable<int> prev_auxi2 { get; set; }
        public Nullable<int> prev_auxi3 { get; set; }
        public Nullable<int> prev_auxi4 { get; set; }
        public System.DateTime prev_fechacreacion { get; set; }
        public int prev_usuariocreacion { get; set; }
        public string prev_terminalcreacion { get; set; }
        public System.DateTime prev_fum { get; set; }
        public int prev_uum { get; set; }
        public string prev_tum { get; set; }
    }
}
