//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_LOG
    {
        public int LOG_CODIGO { get; set; }
        public System.DateTime log_fecha { get; set; }
        public int log_usucodigo { get; set; }
        public string log_frm { get; set; }
        public string log_evento { get; set; }
        public Nullable<int> log_linea { get; set; }
    }
}
