//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_GARANTES
    {
        public int GART_CODIGO { get; set; }
        public string CEDULA_TITULAR { get; set; }
        public string CEDULA { get; set; }
        public string GARANTE { get; set; }
        public string TIPO { get; set; }
        public string NUM_OPERACION { get; set; }
        public string DIRECCION_DOMICILIO { get; set; }
        public string REFERENCIA_DOMICILIO { get; set; }
        public string DIRECCION_TRABAJO { get; set; }
        public string REFERENCIA_TRABAJO { get; set; }
        public string EMAIL_PERSONAL { get; set; }
        public string EMAIL_TRABAJO { get; set; }
    }
}
