//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_CONTACTO
    {
        public int ARCO_CODIGO { get; set; }
        public int ARRE_CODIGO { get; set; }
        public string arco_descripcion { get; set; }
        public bool arco_estado { get; set; }
        public string arco_auxv1 { get; set; }
        public string arco_auxv2 { get; set; }
        public Nullable<int> arco_auxi1 { get; set; }
        public Nullable<int> arco_auxi2 { get; set; }
    
        public virtual SoftCob_RESPUESTA SoftCob_RESPUESTA { get; set; }
    }
}
