//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_ESTRACAB_HISTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_ESTRACAB_HISTO()
        {
            this.SoftCob_ESTRADET_HISTO = new HashSet<SoftCob_ESTRADET_HISTO>();
        }
    
        public int ECHI_CODIGO { get; set; }
        public int LTCA_CODIGO { get; set; }
        public string echi_auxv1 { get; set; }
        public string echi_auxv2 { get; set; }
        public Nullable<int> echi_auxi1 { get; set; }
        public Nullable<int> echi_auxi2 { get; set; }
    
        public virtual SoftCob_LISTATRABAJO_CABECERA SoftCob_LISTATRABAJO_CABECERA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_ESTRADET_HISTO> SoftCob_ESTRADET_HISTO { get; set; }
    }
}
