//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_PERFIL_DEUDOR
    {
        public int PEDE_CODIGO { get; set; }
        public int pede_perscodigo { get; set; }
        public int pede_peaccodigo { get; set; }
        public int pede_peencodigo { get; set; }
        public int pede_peeycodigo { get; set; }
        public int pede_pempcodigo { get; set; }
        public int pede_pemocodigo { get; set; }
        public int pede_peipcodigo { get; set; }
        public string pede_auxv1 { get; set; }
        public string pede_auxv2 { get; set; }
        public string pede_auxv3 { get; set; }
        public Nullable<int> pede_auxi1 { get; set; }
        public Nullable<int> pede_auxi2 { get; set; }
        public Nullable<int> pede_auxi3 { get; set; }
    }
}
