//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_TELEFONOS_CEDENTE
    {
        public int TECE_CODIGO { get; set; }
        public int tece_cedecodigo { get; set; }
        public int tece_perscodigo { get; set; }
        public int tece_referencodigo { get; set; }
        public string tece_numero { get; set; }
        public string tece_tipo { get; set; }
        public string tece_propietario { get; set; }
        public int tece_score { get; set; }
        public bool tece_estado { get; set; }
        public string tece_auxv1 { get; set; }
        public string tece_auxv2 { get; set; }
        public string tece_auxv3 { get; set; }
        public Nullable<int> tece_auxi1 { get; set; }
        public Nullable<int> tece_auxi2 { get; set; }
        public Nullable<int> tece_auxi3 { get; set; }
        public System.DateTime tece_fechacreacion { get; set; }
        public int tece_usuariocreacion { get; set; }
        public string tece_terminalcreacion { get; set; }
    }
}
