//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_REGISTRO_BROADCAST
    {
        public int ENBR_CODIGO { get; set; }
        public Nullable<int> enbr_codigocpce { get; set; }
        public string enbr_catalogo { get; set; }
        public Nullable<System.DateTime> enbr_fechaproceso { get; set; }
        public Nullable<System.DateTime> enbr_fecharegistro { get; set; }
        public Nullable<int> enbr_registros { get; set; }
        public string enbr_computer { get; set; }
        public string enbr_auxv1 { get; set; }
        public string enbr_auxv2 { get; set; }
        public string enbr_auxv3 { get; set; }
        public Nullable<int> enbr_auxi1 { get; set; }
        public Nullable<int> enbr_auxi2 { get; set; }
        public Nullable<int> enbr_auxi3 { get; set; }
    }
}
