//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_ESTADOS_DELYO
    {
        public int PEEY_CODIGO { get; set; }
        public string peey_descripcion { get; set; }
        public bool peey_estado { get; set; }
        public string peey_auxv1 { get; set; }
        public string peey_auxv2 { get; set; }
        public string peey_auxv3 { get; set; }
        public Nullable<int> peey_auxi1 { get; set; }
        public Nullable<int> peey_auxi2 { get; set; }
        public Nullable<int> peey_auxi3 { get; set; }
        public System.DateTime peey_fechacreacion { get; set; }
        public int peey_usuariocreacion { get; set; }
        public string peey_terminalcreacion { get; set; }
        public System.DateTime peey_fum { get; set; }
        public int peey_uum { get; set; }
        public string peey_tum { get; set; }
    }
}
