//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_CAMPOS_SPEECH
    {
        public int CASP_CODIGO { get; set; }
        public string casp_campo { get; set; }
        public string casp_etiqueta { get; set; }
        public string casp_tipo { get; set; }
        public bool casp_estado { get; set; }
        public string casp_auxv1 { get; set; }
        public string casp_auxv2 { get; set; }
        public Nullable<int> casp_auxi1 { get; set; }
        public Nullable<int> casp_auxi2 { get; set; }
        public System.DateTime casp_fechacreacion { get; set; }
        public int casp_usuariocreacion { get; set; }
        public string casp_terminalcreacion { get; set; }
        public System.DateTime casp_fum { get; set; }
        public int casp_uum { get; set; }
        public string casp_tum { get; set; }
    }
}
