//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_BITACORA_DET
    {
        public int BIDE_CODIGO { get; set; }
        public string bica_nombre { get; set; }
        public string bide_tipobitacora { get; set; }
        public string bide_observaciongeneral { get; set; }
        public int bide_gestor { get; set; }
        public string bide_observacionbitacora { get; set; }
        public System.DateTime bide_fechabitacora { get; set; }
        public string bide_horabitacora { get; set; }
        public string bide_turnoactual { get; set; }
        public string bide_turnonuevo { get; set; }
        public int bide_firma { get; set; }
        public string bide_auxv1 { get; set; }
        public string bide_auxv2 { get; set; }
        public string bide_auxv3 { get; set; }
        public string bide_auxv4 { get; set; }
        public string bide_auxv5 { get; set; }
        public Nullable<int> bide_auxi1 { get; set; }
        public Nullable<int> bide_auxi2 { get; set; }
        public Nullable<int> bide_auxi3 { get; set; }
        public Nullable<int> bide_auxi4 { get; set; }
        public Nullable<int> bide_auxi5 { get; set; }
        public System.DateTime bide_fechacreacion { get; set; }
        public string bide_terminalcreacion { get; set; }
    }
}
