//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_CAMPOS_ADICIONALES
    {
        public int CAAD_CODIGO { get; set; }
        public int caad_cedecodigo { get; set; }
        public int caad_cpcecodigo { get; set; }
        public int caad_perscodigo { get; set; }
        public string caad_operacion { get; set; }
        public string caad_campo1 { get; set; }
        public string caad_campo2 { get; set; }
        public string caad_campo3 { get; set; }
        public string caad_campo4 { get; set; }
        public string caad_campo5 { get; set; }
        public string caad_campo6 { get; set; }
        public string caad_campo7 { get; set; }
        public string caad_campo8 { get; set; }
        public string caad_campo9 { get; set; }
        public string caad_campo10 { get; set; }
        public string caad_campo11 { get; set; }
        public string caad_campo12 { get; set; }
        public string caad_campo13 { get; set; }
        public string caad_campo14 { get; set; }
        public string caad_campo15 { get; set; }
        public string caad_campo16 { get; set; }
        public string caad_campo17 { get; set; }
        public string caad_campo18 { get; set; }
        public string caad_campo19 { get; set; }
        public string caad_campo20 { get; set; }
        public string caad_campo21 { get; set; }
        public string caad_campo22 { get; set; }
        public string caad_campo23 { get; set; }
        public string caad_campo24 { get; set; }
        public string caad_campo25 { get; set; }
        public string caad_campo26 { get; set; }
        public string caad_campo27 { get; set; }
        public string caad_campo28 { get; set; }
        public string caad_campo29 { get; set; }
        public string caad_campo30 { get; set; }
    }
}
