//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_GESTORES_LISTASFDA
    {
        public int LFDA_CODIGO { get; set; }
        public int lfda_lista { get; set; }
        public string lfda_grupo { get; set; }
        public string lfda_gestor { get; set; }
        public int lfda_operaciones { get; set; }
        public string lfda_auxv1 { get; set; }
        public string lfda_auxv2 { get; set; }
        public string lfda_auxv3 { get; set; }
        public Nullable<int> lfda_auxi1 { get; set; }
        public Nullable<int> lfda_auxi2 { get; set; }
        public Nullable<int> lfda_auxi3 { get; set; }
    }
}
