//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_ACCESO_CONSULTA_CEDENTES
    {
        public int ACCE_CODIGO { get; set; }
        public int acce_usucodigo { get; set; }
        public int acce_cpcecodigo { get; set; }
        public bool acce_estado { get; set; }
        public string acce_auxv1 { get; set; }
        public string acce_auxv2 { get; set; }
        public string acce_auxv3 { get; set; }
        public Nullable<int> acce_auxi1 { get; set; }
        public Nullable<int> acce_auxi2 { get; set; }
        public Nullable<int> acce_auxi3 { get; set; }
        public System.DateTime acce_fechacreacion { get; set; }
        public int acce_usuariocreacion { get; set; }
        public string acce_terminalcreacion { get; set; }
        public System.DateTime acce_fum { get; set; }
        public int acce_uum { get; set; }
        public string acce_tum { get; set; }
    }
}
