//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_PRODUCTOS_CEDENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_PRODUCTOS_CEDENTE()
        {
            this.SoftCob_CATALOGO_PRODUCTOS_CEDENTE = new HashSet<SoftCob_CATALOGO_PRODUCTOS_CEDENTE>();
        }
    
        public int PRCE_CODIGO { get; set; }
        public int CEDE_CODIGO { get; set; }
        public string prce_producto { get; set; }
        public string prce_descripcion { get; set; }
        public bool prce_estado { get; set; }
        public string prce_auxv1 { get; set; }
        public string prce_auxv2 { get; set; }
        public Nullable<int> prce_auxi1 { get; set; }
        public Nullable<int> prce_auxi2 { get; set; }
    
        public virtual SoftCob_CEDENTE SoftCob_CEDENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_CATALOGO_PRODUCTOS_CEDENTE> SoftCob_CATALOGO_PRODUCTOS_CEDENTE { get; set; }
    }
}
