//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_CONTACTOS_CEDENTE
    {
        public int COCE_CODIGO { get; set; }
        public int CEDE_CODIGO { get; set; }
        public string coce_contacto { get; set; }
        public string coce_cargo { get; set; }
        public string coce_extension { get; set; }
        public string coce_email1 { get; set; }
        public string coce_email2 { get; set; }
        public string coce_celular { get; set; }
        public string coce_auxv1 { get; set; }
        public Nullable<int> coce_auxi1 { get; set; }
    
        public virtual SoftCob_CEDENTE SoftCob_CEDENTE { get; set; }
    }
}
