//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_REGISTRO_ABONOSPAGO
    {
        public int RPAB_CODIGO { get; set; }
        public int rpab_ltcacodigo { get; set; }
        public int rpab_ltdecodigo { get; set; }
        public int rpab_cldecodigo { get; set; }
        public int rpab_gestorasignado { get; set; }
        public System.DateTime rpab_fechapago { get; set; }
        public decimal rpab_valorpago { get; set; }
        public decimal rpab_valorexigible { get; set; }
        public int rpab_araccodigo { get; set; }
        public int rpab_arefcodigo { get; set; }
        public int rpab_arrecodigo { get; set; }
        public int rpab_arcocodigo { get; set; }
        public string rpab_auxv1 { get; set; }
        public string rpab_auxv2 { get; set; }
        public string rpab_auxv3 { get; set; }
        public Nullable<int> rpab_auxi1 { get; set; }
        public Nullable<int> rpab_auxi2 { get; set; }
        public Nullable<int> rpab_auxi3 { get; set; }
        public decimal rpab_auxd1 { get; set; }
        public decimal rpab_auxd2 { get; set; }
        public System.DateTime rpab_fechacreacion { get; set; }
        public int rpab_usuariocreacion { get; set; }
        public string rpab_terminalcreacion { get; set; }
    }
}
