//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_REGISTRO_VOLVERALLAMAR
    {
        public int REVL_CODIGO { get; set; }
        public int revl_ltcacodigo { get; set; }
        public int revl_ltdecodigo { get; set; }
        public int revl_cldecodigo { get; set; }
        public int revl_perscodigo { get; set; }
        public int revl_gestorasignado { get; set; }
        public System.DateTime revl_fechallamar { get; set; }
        public System.TimeSpan revl_horallamar { get; set; }
        public string revl_fechatotal { get; set; }
        public string revl_telefonollamar { get; set; }
        public string revl_tipo { get; set; }
        public string revl_propietario { get; set; }
        public string revl_gestionado { get; set; }
        public string revl_auxv1 { get; set; }
        public string revl_auxv2 { get; set; }
        public string revl_auxv3 { get; set; }
        public Nullable<int> revl_auxi1 { get; set; }
        public Nullable<int> revl_auxi2 { get; set; }
        public Nullable<int> revl_auxi3 { get; set; }
        public System.DateTime revl_fechacreacion { get; set; }
        public int revl_usuariocreacion { get; set; }
        public string revl_terminalcreacion { get; set; }
    }
}
