//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_EXPERIENCIA
    {
        public int EXPE_CODIGO { get; set; }
        public int EMPL_CODIGO { get; set; }
        public string expe_empresa { get; set; }
        public System.DateTime expe_desde { get; set; }
        public System.DateTime expe_hasta { get; set; }
        public string expe_cargo { get; set; }
        public string expe_descripcion { get; set; }
        public string expe_motivo { get; set; }
    
        public virtual SoftCob_EMPLOYEE SoftCob_EMPLOYEE { get; set; }
    }
}
