//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_SPEECH_CABECERA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_SPEECH_CABECERA()
        {
            this.SoftCob_SPEECH_DETALLE = new HashSet<SoftCob_SPEECH_DETALLE>();
        }
    
        public int SPCA_CODIGO { get; set; }
        public int spca_cedecodigo { get; set; }
        public int spca_cpcecodigo { get; set; }
        public string spca_speechbv { get; set; }
        public bool spca_estado { get; set; }
        public string spca_auxv1 { get; set; }
        public string spca_auxv2 { get; set; }
        public Nullable<int> spca_auxi1 { get; set; }
        public Nullable<int> spca_auxi2 { get; set; }
        public System.DateTime spca_fechacreacion { get; set; }
        public int spca_usuariocreacion { get; set; }
        public string spca_terminalcreacion { get; set; }
        public System.DateTime spca_fum { get; set; }
        public int spca_uum { get; set; }
        public string spca_tum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_SPEECH_DETALLE> SoftCob_SPEECH_DETALLE { get; set; }
    }
}
