//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_DEUDOR_REFERENCIAS
    {
        public int DERE_CODIGO { get; set; }
        public int pers_codigo { get; set; }
        public string dere_numdocumento { get; set; }
        public string dere_tiporeferencia { get; set; }
        public string dere_nombrereferencia { get; set; }
        public string dere_apellidoreferencia { get; set; }
        public string dere_auxv1 { get; set; }
        public string dere_auxv2 { get; set; }
        public string dere_auxv3 { get; set; }
        public Nullable<int> dere_auxi1 { get; set; }
        public Nullable<int> dere_auxi2 { get; set; }
        public Nullable<int> dere_auxi3 { get; set; }
        public System.DateTime dere_fum { get; set; }
        public int dere_uum { get; set; }
        public string dere_tum { get; set; }
        public System.DateTime dere_fechacreacion { get; set; }
        public int dere_usuariocreacion { get; set; }
        public string dere_terminalcreacion { get; set; }
    }
}
