//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_PARAMETRO_DETALLE
    {
        public int PADE_CODIGO { get; set; }
        public int PARA_CODIGO { get; set; }
        public string pade_nombre { get; set; }
        public string pade_valorV { get; set; }
        public int pade_valorI { get; set; }
        public string pade_auxv1 { get; set; }
        public string pade_auxv2 { get; set; }
        public Nullable<int> pade_auxi1 { get; set; }
        public Nullable<int> pade_auxi2 { get; set; }
        public Nullable<int> pade_orden { get; set; }
        public bool pade_estado { get; set; }
    
        public virtual SoftCob_PARAMETRO_CABECERA SoftCob_PARAMETRO_CABECERA { get; set; }
    }
}
