//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_LISTATRABAJO_ACTIVAS
    {
        public int LSAC_CODIGO { get; set; }
        public int lsac_listatrabajo { get; set; }
        public int lsac_gestorasignado { get; set; }
        public bool lsac_estado { get; set; }
        public string lsac_auxv1 { get; set; }
        public string lsac_auxv2 { get; set; }
        public Nullable<int> lsac_auxi1 { get; set; }
        public Nullable<int> lsac_auxi2 { get; set; }
    }
}
