//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_LISTATRABAJO_DETALLE
    {
        public int LTDE_CODIGO { get; set; }
        public int LTCA_CODIGO { get; set; }
        public int ltde_cldecodigo { get; set; }
        public int ltde_perscodigo { get; set; }
        public int ltde_gestorasignado { get; set; }
        public bool ltde_estado { get; set; }
        public string ltde_gestionado { get; set; }
        public string ltde_auxv1 { get; set; }
        public string ltde_auxv2 { get; set; }
        public string ltde_auxv3 { get; set; }
        public Nullable<int> ltde_auxi1 { get; set; }
        public Nullable<int> ltde_auxi2 { get; set; }
        public Nullable<int> ltde_auxi3 { get; set; }
    
        public virtual SoftCob_LISTATRABAJO_CABECERA SoftCob_LISTATRABAJO_CABECERA { get; set; }
    }
}
