//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_OTROSESTUDIOS
    {
        public int OTES_CODIGO { get; set; }
        public int EMPL_CODIGO { get; set; }
        public string otes_institucion { get; set; }
        public Nullable<System.DateTime> otes_oidesde { get; set; }
        public Nullable<System.DateTime> otes_oihasta { get; set; }
        public string otes_tituloinstituto { get; set; }
    
        public virtual SoftCob_EMPLOYEE SoftCob_EMPLOYEE { get; set; }
    }
}
