//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_PERFIL_ACTITUDINAL
    {
        public int PEAC_CODIGO { get; set; }
        public string peac_descripcion { get; set; }
        public bool peac_estado { get; set; }
        public string peac_auxv1 { get; set; }
        public string peac_auxv2 { get; set; }
        public string peac_auxv3 { get; set; }
        public Nullable<int> peac_auxi1 { get; set; }
        public Nullable<int> peac_auxi2 { get; set; }
        public Nullable<int> peac_auxi3 { get; set; }
        public System.DateTime peac_fechacreacion { get; set; }
        public int peac_usuariocreacion { get; set; }
        public string peac_terminalcreacion { get; set; }
        public System.DateTime peac_fum { get; set; }
        public int peac_uum { get; set; }
        public string peac_tum { get; set; }
    }
}
