//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_SCORETELEFONO
    {
        public int SCTE_CODIGO { get; set; }
        public string scte_cedula { get; set; }
        public string scte_tipodato { get; set; }
        public string scte_dato { get; set; }
    }
}
