//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_OPCIONESMULTIPLES_LISTA
    {
        public int REOM_CODIGO { get; set; }
        public int LTCA_CODIGO { get; set; }
        public string reom_codigos { get; set; }
        public string reom_auxv1 { get; set; }
        public string reom_auxv2 { get; set; }
        public string reom_auxv3 { get; set; }
        public Nullable<int> reom_auxi1 { get; set; }
        public Nullable<int> reom_auxi2 { get; set; }
        public Nullable<int> reom_auxi3 { get; set; }
    
        public virtual SoftCob_LISTATRABAJO_CABECERA SoftCob_LISTATRABAJO_CABECERA { get; set; }
    }
}
