//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_ESTUDIOS
    {
        public int ESTU_CODIGO { get; set; }
        public int EMPL_CODIGO { get; set; }
        public string estu_primaria { get; set; }
        public string estu_apdesde { get; set; }
        public string estu_aphasta { get; set; }
        public string estu_secundaria { get; set; }
        public string estu_asdesde { get; set; }
        public string estu_ashasta { get; set; }
        public string estu_titulosecundaria { get; set; }
        public string estu_superior { get; set; }
        public string estu_audesde { get; set; }
        public string estu_auhasta { get; set; }
        public string estu_titulosuperior { get; set; }
    
        public virtual SoftCob_EMPLOYEE SoftCob_EMPLOYEE { get; set; }
    }
}
