//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_REGION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_REGION()
        {
            this.SoftCob_PROVINCIA = new HashSet<SoftCob_PROVINCIA>();
        }
    
        public int REGI_CODIGO { get; set; }
        public string regi_nombre { get; set; }
        public Nullable<bool> regi_estado { get; set; }
        public System.DateTime regi_fechacreacion { get; set; }
        public int regi_usuariocreacion { get; set; }
        public System.DateTime regi_fum { get; set; }
        public int regi_uum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_PROVINCIA> SoftCob_PROVINCIA { get; set; }
    }
}
