//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_BRENCHMESDET
    {
        public int BRMD_CODIGO { get; set; }
        public int BRMC_CODIGO { get; set; }
        public int brmd_operaciones { get; set; }
        public decimal brmd_montototal { get; set; }
        public decimal brmd_totalexigible { get; set; }
        public decimal brmd_porcentaje { get; set; }
        public decimal brmd_presupuesto { get; set; }
        public decimal brmd_porcentajecumplido { get; set; }
        public decimal brmd_presupuestocumplido { get; set; }
        public string brmd_brench { get; set; }
        public int brmd_rangoinicial { get; set; }
        public int brmd_rangofinal { get; set; }
        public int brmd_orden { get; set; }
        public string brmd_auxv1 { get; set; }
        public string brmd_auxv2 { get; set; }
        public string brmd_auxv3 { get; set; }
        public Nullable<int> brmd_auxi1 { get; set; }
        public Nullable<int> brmd_auxi2 { get; set; }
        public Nullable<int> brmd_auxi3 { get; set; }
    
        public virtual SoftCob_BRENCHMESCAB SoftCob_BRENCHMESCAB { get; set; }
    }
}
