//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_TAREA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_TAREA()
        {
            this.SoftCob_MENU_TAREA = new HashSet<SoftCob_MENU_TAREA>();
        }
    
        public int TARE_CODIGO { get; set; }
        public int empr_codigo { get; set; }
        public string tare_descripcion { get; set; }
        public string tare_programa { get; set; }
        public bool tare_estado { get; set; }
        public int tare_orden { get; set; }
        public string tare_auxv1 { get; set; }
        public string tare_auxv2 { get; set; }
        public string tare_auxv3 { get; set; }
        public Nullable<int> tare_auxi1 { get; set; }
        public Nullable<int> tare_auxi2 { get; set; }
        public Nullable<int> tare_auxi3 { get; set; }
        public System.DateTime tare_fechacreacion { get; set; }
        public int tare_usuariocreacion { get; set; }
        public string tare_terminalcreacion { get; set; }
        public System.DateTime tare_fum { get; set; }
        public int tare_uum { get; set; }
        public string tare_tum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_MENU_TAREA> SoftCob_MENU_TAREA { get; set; }
    }
}
