//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_SCORING_TELEFONICO
    {
        public int SCTE_CODIGO { get; set; }
        public int scte_perscodigo { get; set; }
        public string scte_telefono { get; set; }
        public int scte_araccodigo { get; set; }
        public int scte_arefcodigo { get; set; }
        public int scte_arrecodigo { get; set; }
        public int scte_arcocodigo { get; set; }
        public int scte_noefectivo { get; set; }
        public string scte_auxv1 { get; set; }
        public string scte_auxv2 { get; set; }
        public string scte_auxv3 { get; set; }
        public Nullable<int> scte_auxi1 { get; set; }
        public Nullable<int> scte_auxi2 { get; set; }
        public Nullable<int> scte_auxi3 { get; set; }
        public System.DateTime scte_fechacreacion { get; set; }
        public int scte_usuariocreacion { get; set; }
        public string scte_terminalcreacion { get; set; }
    }
}
