//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_PERFIL_MENU_TAREA
    {
        public int PEMT_CODIGO { get; set; }
        public int PERF_CODIGO { get; set; }
        public int META_CODIGO { get; set; }
        public int empr_codigo { get; set; }
        public bool pemt_estado { get; set; }
        public string pemt_auxv1 { get; set; }
        public string pemt_auxv2 { get; set; }
        public string pemt_auxv3 { get; set; }
        public Nullable<int> pemt_auxi1 { get; set; }
        public Nullable<int> pemt_auxi2 { get; set; }
        public Nullable<int> pemt_auxi3 { get; set; }
    
        public virtual SoftCob_MENU_TAREA SoftCob_MENU_TAREA { get; set; }
        public virtual SoftCob_PERFIL SoftCob_PERFIL { get; set; }
    }
}
