//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_GESTOR_SUPERVISOR
    {
        public int GEST_CODIGO { get; set; }
        public int SUPE_CODIGO { get; set; }
        public int USUA_CODIGO { get; set; }
        public bool gest_estado { get; set; }
        public string gest_auxv1 { get; set; }
        public string gest_auxv2 { get; set; }
        public string gest_auxv3 { get; set; }
        public Nullable<int> gest_auxi1 { get; set; }
        public Nullable<int> gest_auxi2 { get; set; }
        public Nullable<int> gest_auxi3 { get; set; }
        public System.DateTime gest_fechacreacion { get; set; }
        public int gest_usuariocreacion { get; set; }
        public string gest_terminalcreacion { get; set; }
        public System.DateTime gest_fum { get; set; }
        public int gest_uum { get; set; }
        public string gest_tum { get; set; }
    
        public virtual SoftCob_USUARIO SoftCob_USUARIO { get; set; }
        public virtual SoftCob_SUPERVISORES SoftCob_SUPERVISORES { get; set; }
    }
}
