//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_AGENCIAS_CEDENTE
    {
        public int AGEN_CODIGO { get; set; }
        public int CEDE_CODIGO { get; set; }
        public string agen_codigoagencia { get; set; }
        public string agen_nombreagencia { get; set; }
        public string agen_sucursal { get; set; }
        public string agen_zona { get; set; }
        public bool agen_estado { get; set; }
        public string agen_auxv1 { get; set; }
        public string agen_auxv2 { get; set; }
        public Nullable<int> agen_auxi1 { get; set; }
        public Nullable<int> agen_auxi2 { get; set; }
    
        public virtual SoftCob_CEDENTE SoftCob_CEDENTE { get; set; }
    }
}
