//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_BRENCHGESTORCAB
    {
        public int GEBC_CODIGO { get; set; }
        public int gebc_cedecodigo { get; set; }
        public int gebc_cpcecodigo { get; set; }
        public int gebc_gestor { get; set; }
        public System.DateTime gebc_fechapago { get; set; }
        public decimal gebc_totalpago { get; set; }
        public int gebc_aniobrench { get; set; }
        public int gebc_mesbrench { get; set; }
        public string gebc_auxv1 { get; set; }
        public string gebc_auxv2 { get; set; }
        public string gebc_auxv3 { get; set; }
        public string gebc_auxv4 { get; set; }
        public Nullable<int> gebc_auxi1 { get; set; }
        public Nullable<int> gebc_auxi2 { get; set; }
        public Nullable<int> gebc_auxi3 { get; set; }
        public Nullable<int> gebc_auxi4 { get; set; }
        public Nullable<decimal> gebc_auxd1 { get; set; }
        public Nullable<decimal> gebc_auxd2 { get; set; }
        public Nullable<decimal> gebc_auxd3 { get; set; }
        public Nullable<decimal> gebc_auxd4 { get; set; }
        public System.DateTime gebc_fechacreacion { get; set; }
        public int gebc_usuariocreacion { get; set; }
        public string gebc_terminalcreacion { get; set; }
        public System.DateTime gebc_fum { get; set; }
        public int gebc_uum { get; set; }
        public string gebc_tum { get; set; }
    }
}
