//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_ACCESOLISTA
    {
        public int ACLI_CODIGO { get; set; }
        public int acli_cedecodigo { get; set; }
        public int acli_usucodigo { get; set; }
        public string acli_listaactivada { get; set; }
        public string acli_auxv1 { get; set; }
        public string acli_auxv2 { get; set; }
        public string acli_auxv3 { get; set; }
        public Nullable<int> acli_auxi1 { get; set; }
        public Nullable<int> acli_auxi2 { get; set; }
        public Nullable<int> acli_auxi3 { get; set; }
        public System.DateTime acli_fechacreacion { get; set; }
        public int acli_usuariocreacion { get; set; }
        public string acli_terminalcreacion { get; set; }
        public System.DateTime acli_fum { get; set; }
        public int acli_uum { get; set; }
        public string acli_tum { get; set; }
    }
}
