//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_LOGO_CEDENTES
    {
        public int CFCE_CODIGO { get; set; }
        public int cofe_usucodigo { get; set; }
        public string cofe_pathlogo { get; set; }
        public bool cofe_estatus { get; set; }
        public string cofe_auxv1 { get; set; }
        public string cofe_auxv2 { get; set; }
        public Nullable<int> cofe_auxi1 { get; set; }
        public Nullable<int> cofe_auxi2 { get; set; }
        public System.DateTime cofe_fechacreacion { get; set; }
        public int cofe_usuariocreacion { get; set; }
        public string cofe_terminalcreacion { get; set; }
        public System.DateTime cofe_fum { get; set; }
        public int cofe_uum { get; set; }
        public string cofe_tum { get; set; }
    }
}
