//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_CONFIGURACION_PHONE
    {
        public int COSF_CODIGO { get; set; }
        public int USUA_CODIGO { get; set; }
        public Nullable<int> cosf_extension { get; set; }
        public string cosf_password { get; set; }
        public string cosf_dominio { get; set; }
        public Nullable<int> cosf_puerto { get; set; }
        public string cosf_auxv1 { get; set; }
        public string cosf_auxv2 { get; set; }
        public string cosf_auxv3 { get; set; }
        public string cosf_auxv4 { get; set; }
        public string cosf_auxv5 { get; set; }
        public Nullable<int> cosf_auxi1 { get; set; }
        public Nullable<int> cosf_auxi2 { get; set; }
        public Nullable<int> cosf_auxi3 { get; set; }
        public Nullable<int> cosf_auxi4 { get; set; }
        public Nullable<int> cosf_auxi5 { get; set; }
    
        public virtual SoftCob_USUARIO SoftCob_USUARIO { get; set; }
    }
}
