//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_USUARIO()
        {
            this.SoftCob_GESTOR_SUPERVISOR = new HashSet<SoftCob_GESTOR_SUPERVISOR>();
            this.SoftCob_LOGUEO_TIEMPOS = new HashSet<SoftCob_LOGUEO_TIEMPOS>();
            this.SoftCob_LOGUEO_TIEMPOS1 = new HashSet<SoftCob_LOGUEO_TIEMPOS>();
        }
    
        public int USUA_CODIGO { get; set; }
        public int PERF_CODIGO { get; set; }
        public int DEPA_CODIGO { get; set; }
        public int empr_codigo { get; set; }
        public Nullable<int> empl_codigo { get; set; }
        public string usua_tipousuario { get; set; }
        public string usua_nombres { get; set; }
        public string usua_apellidos { get; set; }
        public string usua_cedula { get; set; }
        public string usua_login { get; set; }
        public string usua_password { get; set; }
        public bool usua_estado { get; set; }
        public Nullable<int> usua_contador { get; set; }
        public bool usua_caducapass { get; set; }
        public System.DateTime usua_fechacaduca { get; set; }
        public bool usua_cambiarpass { get; set; }
        public bool usua_statuslogin { get; set; }
        public bool usua_permisosespeciales { get; set; }
        public string usua_terminallogin { get; set; }
        public string usua_logobienvenida { get; set; }
        public string usua_logomenu { get; set; }
        public string usua_mail { get; set; }
        public string usua_celular { get; set; }
        public byte[] usua_foto { get; set; }
        public string usua_imagepath { get; set; }
        public string usua_imagefullpath { get; set; }
        public string usua_auxv1 { get; set; }
        public string usua_auxv2 { get; set; }
        public string usua_auxv3 { get; set; }
        public string usua_auxv4 { get; set; }
        public string usua_auxv5 { get; set; }
        public Nullable<int> usua_auxi1 { get; set; }
        public Nullable<int> usua_auxi2 { get; set; }
        public Nullable<int> usua_auxi3 { get; set; }
        public Nullable<int> usua_auxi4 { get; set; }
        public Nullable<int> usua_auxi5 { get; set; }
        public Nullable<System.DateTime> usua_fechacreacion { get; set; }
        public Nullable<int> usua_usuariocreacion { get; set; }
        public string usua_terminalcreacion { get; set; }
        public Nullable<System.DateTime> usua_fum { get; set; }
        public Nullable<int> usua_uum { get; set; }
        public string usua_tum { get; set; }
    
        public virtual SoftCob_DEPARTAMENTO SoftCob_DEPARTAMENTO { get; set; }
        public virtual SoftCob_PERFIL SoftCob_PERFIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_GESTOR_SUPERVISOR> SoftCob_GESTOR_SUPERVISOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_LOGUEO_TIEMPOS> SoftCob_LOGUEO_TIEMPOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_LOGUEO_TIEMPOS> SoftCob_LOGUEO_TIEMPOS1 { get; set; }
    }
}
