//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_DEPARTAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_DEPARTAMENTO()
        {
            this.SoftCob_USUARIO = new HashSet<SoftCob_USUARIO>();
        }
    
        public int DEPA_CODIGO { get; set; }
        public int empr_codigo { get; set; }
        public string depa_descripcion { get; set; }
        public bool depa_estado { get; set; }
        public string depa_auxv1 { get; set; }
        public string depa_auxv2 { get; set; }
        public string depa_auxv3 { get; set; }
        public Nullable<int> depa_auxi1 { get; set; }
        public Nullable<int> depa_auxi2 { get; set; }
        public Nullable<int> depa_auxi3 { get; set; }
        public System.DateTime depa_fechacreacion { get; set; }
        public int depa_usuariocreacion { get; set; }
        public string depa_terminalcreacion { get; set; }
        public System.DateTime depa_fum { get; set; }
        public int depa_uum { get; set; }
        public string depa_tum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_USUARIO> SoftCob_USUARIO { get; set; }
    }
}
