//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_CITACIONES_REV
    {
        public int CREV_CODIGO { get; set; }
        public int pers_codigo { get; set; }
        public System.DateTime crev_fechareserva { get; set; }
        public int chor_codigo { get; set; }
        public int crev_usuareserva { get; set; }
        public string crev_auxv1 { get; set; }
        public string crev_auxv2 { get; set; }
        public string crev_auxv3 { get; set; }
        public Nullable<int> crev_auxi1 { get; set; }
        public Nullable<int> crev_auxi2 { get; set; }
        public Nullable<int> crev_auxi3 { get; set; }
        public System.DateTime crev_fechacreacion { get; set; }
        public int crev_usuariocreacion { get; set; }
        public string crev_terminalcreacion { get; set; }
    }
}
