//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_PAGOSBRENCH_CAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_PAGOSBRENCH_CAB()
        {
            this.SoftCob_PAGOSBRENCH_DET = new HashSet<SoftCob_PAGOSBRENCH_DET>();
        }
    
        public int PBCA_CODIGO { get; set; }
        public int pbca_cedecodigo { get; set; }
        public int pbca_cpcecodigo { get; set; }
        public int pbca_gestorasignado { get; set; }
        public System.DateTime pbca_fechaproceso { get; set; }
        public int pbca_brenchanio { get; set; }
        public int pbca_brenchmes { get; set; }
        public string pbca_brenchetiqueta { get; set; }
        public string pbca_auxv1 { get; set; }
        public string pbca_auxv2 { get; set; }
        public string pbca_auxv3 { get; set; }
        public Nullable<int> pbca_auxi1 { get; set; }
        public Nullable<int> pbca_auxi2 { get; set; }
        public Nullable<int> pbca_auxi3 { get; set; }
        public System.DateTime pbca_fechacreacion { get; set; }
        public int pbca_usuariocreacion { get; set; }
        public string pbca_terminalcreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_PAGOSBRENCH_DET> SoftCob_PAGOSBRENCH_DET { get; set; }
    }
}
