//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_METAPROGRAMAS
    {
        public int PEMP_CODIGO { get; set; }
        public string pemp_descripcion { get; set; }
        public bool pemp_estado { get; set; }
        public string pemp_auxv1 { get; set; }
        public string pemp_auxv2 { get; set; }
        public string pemp_auxv3 { get; set; }
        public Nullable<int> pemp_auxi1 { get; set; }
        public Nullable<int> pemp_auxi2 { get; set; }
        public Nullable<int> pemp_auxi3 { get; set; }
        public System.DateTime pemp_fechacreacion { get; set; }
        public int pemp_usuariocreacion { get; set; }
        public string pemp_terminalcreacion { get; set; }
        public System.DateTime pemp_fum { get; set; }
        public int pemp_uum { get; set; }
        public string pemp_tum { get; set; }
    }
}
