//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_BRENCHDET
    {
        public int BRDE_CODIGO { get; set; }
        public int BRCH_CODIGO { get; set; }
        public int brde_rangoinicial { get; set; }
        public int brde_rangofinal { get; set; }
        public string brde_etiqueta { get; set; }
        public int brde_orden { get; set; }
        public bool brde_estado { get; set; }
        public string brde_auxv1 { get; set; }
        public string brde_auxv2 { get; set; }
        public string brde_auxv3 { get; set; }
        public Nullable<int> brde_auxi1 { get; set; }
        public Nullable<int> brde_auxi2 { get; set; }
        public Nullable<int> brde_auxi3 { get; set; }
    
        public virtual SoftCob_BRENCH SoftCob_BRENCH { get; set; }
    }
}
