//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_MENU()
        {
            this.SoftCob_MENU_TAREA = new HashSet<SoftCob_MENU_TAREA>();
        }
    
        public int MENU_CODIGO { get; set; }
        public int empr_codigo { get; set; }
        public string menu_descripcion { get; set; }
        public int menu_nivel { get; set; }
        public bool menu_estado { get; set; }
        public int menu_orden { get; set; }
        public string menu_auxv1 { get; set; }
        public string menu_auxv2 { get; set; }
        public string menu_auxv3 { get; set; }
        public Nullable<int> menu_auxi1 { get; set; }
        public Nullable<int> menu_auxi2 { get; set; }
        public Nullable<int> menu_auxi3 { get; set; }
        public System.DateTime menu_fechacreacion { get; set; }
        public int menu_usuariocreacion { get; set; }
        public string menu_terminalcreacion { get; set; }
        public System.DateTime menu_fum { get; set; }
        public int menu_uum { get; set; }
        public string menu_tum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_MENU_TAREA> SoftCob_MENU_TAREA { get; set; }
    }
}
