//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_ESTILOS_NEGOCIACION
    {
        public int PEEN_CODIGO { get; set; }
        public string peen_descripcion { get; set; }
        public bool peen_estado { get; set; }
        public string peen_auxv1 { get; set; }
        public string peen_auxv2 { get; set; }
        public string peen_auxv3 { get; set; }
        public Nullable<int> peen_auxi1 { get; set; }
        public Nullable<int> peen_auxi2 { get; set; }
        public Nullable<int> peen_auxi3 { get; set; }
        public System.DateTime peen_fechacreacion { get; set; }
        public int peen_usuariocreacion { get; set; }
        public string peen_terminalcreacion { get; set; }
        public System.DateTime peen_fum { get; set; }
        public int peen_uum { get; set; }
        public string peen_tum { get; set; }
    }
}
