//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_ACCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_ACCION()
        {
            this.SoftCob_EFECTO = new HashSet<SoftCob_EFECTO>();
        }
    
        public int ARAC_CODIGO { get; set; }
        public int CPCE_CODIGO { get; set; }
        public string arac_descripcion { get; set; }
        public bool arac_estado { get; set; }
        public bool arac_contacto { get; set; }
        public string arac_auxv1 { get; set; }
        public string arac_auxv2 { get; set; }
        public Nullable<int> arac_auxi1 { get; set; }
        public Nullable<int> arac_auxi2 { get; set; }
        public Nullable<System.DateTime> arac_fechacreacion { get; set; }
        public Nullable<int> arac_usuariocracion { get; set; }
        public string arac_terminalcreacion { get; set; }
        public Nullable<System.DateTime> arac_fum { get; set; }
        public Nullable<int> arac_uum { get; set; }
        public string arac_tum { get; set; }
    
        public virtual SoftCob_CATALOGO_PRODUCTOS_CEDENTE SoftCob_CATALOGO_PRODUCTOS_CEDENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_EFECTO> SoftCob_EFECTO { get; set; }
    }
}
