//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_LOGUEO_TIEMPOS
    {
        public int LOTI_CODIGO { get; set; }
        public int USUA_CODIGO { get; set; }
        public int empr_codigo { get; set; }
        public int cpce_codigo { get; set; }
        public int ltca_codigo { get; set; }
        public string loti_tipologueo { get; set; }
        public System.DateTime loti_fechalogueo { get; set; }
        public System.TimeSpan loti_horalogueo { get; set; }
        public System.DateTime loti_fechacompleta { get; set; }
        public string loti_auxv1 { get; set; }
        public string loti_auxv2 { get; set; }
        public string loti_auxv3 { get; set; }
        public string loti_auxv4 { get; set; }
        public string loti_auxv5 { get; set; }
        public Nullable<int> loti_auxi1 { get; set; }
        public Nullable<int> loti_auxi2 { get; set; }
        public Nullable<int> loti_auxi3 { get; set; }
        public Nullable<int> loti_auxi4 { get; set; }
        public Nullable<int> loti_auxi5 { get; set; }
        public Nullable<System.DateTime> loti_auxd1 { get; set; }
        public Nullable<System.DateTime> loti_auxd2 { get; set; }
        public Nullable<System.DateTime> loti_auxd3 { get; set; }
        public Nullable<System.DateTime> loti_auxd4 { get; set; }
        public Nullable<System.DateTime> loti_auxd5 { get; set; }
        public System.DateTime loti_fechacreacion { get; set; }
        public int loti_usuariocreacion { get; set; }
        public string loti_terminalcreacion { get; set; }
    
        public virtual SoftCob_USUARIO SoftCob_USUARIO { get; set; }
        public virtual SoftCob_USUARIO SoftCob_USUARIO1 { get; set; }
    }
}
