//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_IMPULSORES
    {
        public int PEIP_CODIGO { get; set; }
        public string peip_descripcion { get; set; }
        public bool peip_estado { get; set; }
        public string peip_auxv1 { get; set; }
        public string peip_auxv2 { get; set; }
        public string peip_auxv3 { get; set; }
        public Nullable<int> peip_auxi1 { get; set; }
        public Nullable<int> peip_auxi2 { get; set; }
        public Nullable<int> peip_auxi3 { get; set; }
        public System.DateTime peip_fechacreacion { get; set; }
        public int peip_usuariocreacion { get; set; }
        public string peip_terminalcreacion { get; set; }
        public System.DateTime peip_fum { get; set; }
        public int peip_uum { get; set; }
        public string peip_tum { get; set; }
    }
}
