//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_EVALUACION_CAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_EVALUACION_CAB()
        {
            this.SoftCob_EVALUACION_DET = new HashSet<SoftCob_EVALUACION_DET>();
            this.SoftCob_EVALUACION_USU = new HashSet<SoftCob_EVALUACION_USU>();
        }
    
        public int EVCA_CODIGO { get; set; }
        public string evca_evaluacion { get; set; }
        public string evca_descripcion { get; set; }
        public System.DateTime evca_fechainicio { get; set; }
        public System.DateTime evca_fechafin { get; set; }
        public bool evca_estado { get; set; }
        public string evca_auxv1 { get; set; }
        public string evca_auxv2 { get; set; }
        public string evca_auxv3 { get; set; }
        public Nullable<int> evca_auxi1 { get; set; }
        public Nullable<int> evca_auxi2 { get; set; }
        public Nullable<int> evca_auxi3 { get; set; }
        public System.DateTime evca_fechacreacion { get; set; }
        public int evca_usuariocreacion { get; set; }
        public string evca_terminalcreacion { get; set; }
        public System.DateTime evca_fum { get; set; }
        public int evca_uum { get; set; }
        public string evca_tum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_EVALUACION_DET> SoftCob_EVALUACION_DET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_EVALUACION_USU> SoftCob_EVALUACION_USU { get; set; }
    }
}
