//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_TABLAS_BDD
    {
        public int TABD_CODIGO { get; set; }
        public string tadb_nombre { get; set; }
        public System.DateTime tadb_createdate { get; set; }
        public int tadb_numerocampos { get; set; }
        public int tadb_objectid { get; set; }
        public bool tadb_estado { get; set; }
        public string tadb_auxv1 { get; set; }
        public string tadb_auxv2 { get; set; }
        public string tadb_auxv3 { get; set; }
        public Nullable<int> tadb_auxi1 { get; set; }
        public Nullable<int> tadb_auxi2 { get; set; }
        public Nullable<int> tadb_auxi3 { get; set; }
        public System.DateTime tadb_fechacreacion { get; set; }
        public int tadb_usuariocreacion { get; set; }
        public string tadb_terminalcreacion { get; set; }
        public System.DateTime tadb_fum { get; set; }
        public int tadb_uum { get; set; }
        public string tadb_tum { get; set; }
    }
}
