//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_PARAMETRO_CABECERA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_PARAMETRO_CABECERA()
        {
            this.SoftCob_PARAMETRO_DETALLE = new HashSet<SoftCob_PARAMETRO_DETALLE>();
        }
    
        public int PARA_CODIGO { get; set; }
        public string para_nombre { get; set; }
        public string para_descripcion { get; set; }
        public bool para_estado { get; set; }
        public string para_auxv1 { get; set; }
        public string para_auxiv2 { get; set; }
        public Nullable<int> para_auxii1 { get; set; }
        public Nullable<int> para_auxii2 { get; set; }
        public System.DateTime para_fechacreacion { get; set; }
        public int para_usuariocreacion { get; set; }
        public string para_terminalcreacion { get; set; }
        public System.DateTime para_fum { get; set; }
        public int para_uum { get; set; }
        public string para_tum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_PARAMETRO_DETALLE> SoftCob_PARAMETRO_DETALLE { get; set; }
    }
}
