//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_RESPUESTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_RESPUESTA()
        {
            this.SoftCob_CONTACTO = new HashSet<SoftCob_CONTACTO>();
        }
    
        public int ARRE_CODIGO { get; set; }
        public int AREF_CODIGO { get; set; }
        public string arre_descripcion { get; set; }
        public bool arre_estado { get; set; }
        public bool arre_pago { get; set; }
        public bool arre_llamar { get; set; }
        public string arre_auxv1 { get; set; }
        public string arre_auxv2 { get; set; }
        public Nullable<int> arre_auxi1 { get; set; }
        public Nullable<int> arre_auxi2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_CONTACTO> SoftCob_CONTACTO { get; set; }
        public virtual SoftCob_EFECTO SoftCob_EFECTO { get; set; }
    }
}
