//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_CITACIONES_DET
    {
        public int HCIT_CODIGO { get; set; }
        public int CITA_CODIGO { get; set; }
        public string hcit_estado { get; set; }
        public int hcit_usuaregistro { get; set; }
        public System.DateTime hcit_fecharegistro { get; set; }
        public int chor_hora { get; set; }
        public Nullable<decimal> hcit_valorregistro { get; set; }
        public string hcit_tipoconvenio { get; set; }
        public string hcit_observacion { get; set; }
        public Nullable<bool> hcit_whatsapp { get; set; }
        public string hcit_celular { get; set; }
        public Nullable<bool> hcit_email { get; set; }
        public string hcit_correo { get; set; }
        public Nullable<bool> hcit_terreno { get; set; }
        public string hcit_direccion { get; set; }
        public string hcit_referencia { get; set; }
        public string hcit_telefono { get; set; }
        public string hcit_auxv1 { get; set; }
        public string hcit_auxv2 { get; set; }
        public string hcit_auxv3 { get; set; }
        public string hcit_auxv4 { get; set; }
        public string hcit_auxv5 { get; set; }
        public string hcit_auxv6 { get; set; }
        public string hcit_auxv7 { get; set; }
        public string hcit_auxv8 { get; set; }
        public string hcit_auxv9 { get; set; }
        public string hcit_auxv10 { get; set; }
        public Nullable<int> hcit_auxi1 { get; set; }
        public Nullable<int> hcit_auxi2 { get; set; }
        public Nullable<int> hcit_auxi3 { get; set; }
        public Nullable<int> hcit_auxi4 { get; set; }
        public Nullable<int> hcit_auxi5 { get; set; }
        public System.DateTime hcit_fechacreacion { get; set; }
        public int hcit_usuariocreacion { get; set; }
        public string hcit_terminalcreacion { get; set; }
    
        public virtual SoftCob_CITACIONES_CAB SoftCob_CITACIONES_CAB { get; set; }
    }
}
