//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_MODALIDADES
    {
        public int PEMO_CODIGO { get; set; }
        public string pemo_descripcion { get; set; }
        public bool pemo_estado { get; set; }
        public string pemo_auxv1 { get; set; }
        public string pemo_auxv2 { get; set; }
        public string pemo_auxv3 { get; set; }
        public Nullable<int> pemo_auxi1 { get; set; }
        public Nullable<int> pemo_auxi2 { get; set; }
        public Nullable<int> pemo_auxi3 { get; set; }
        public System.DateTime pemo_fechacreacion { get; set; }
        public int pemo_usuariocreacion { get; set; }
        public string pemo_terminalcreacion { get; set; }
        public System.DateTime pemo_fum { get; set; }
        public int pemo_uum { get; set; }
        public string pemo_tum { get; set; }
    }
}
