//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_IDIOMAS
    {
        public int IDIO_CODIGO { get; set; }
        public int EMPL_CODIGO { get; set; }
        public string idio_idioma { get; set; }
        public string idio_nivelH { get; set; }
        public string idio_nivelE { get; set; }
    
        public virtual SoftCob_EMPLOYEE SoftCob_EMPLOYEE { get; set; }
    }
}
