//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_SPEECH_DETALLE
    {
        public int SPDE_CODIGO { get; set; }
        public int SPCA_CODIGO { get; set; }
        public int spde_araccodigo { get; set; }
        public int spde_arefcodigo { get; set; }
        public int spde_arrecodigo { get; set; }
        public int spde_arcocodigo { get; set; }
        public string spde_speechad { get; set; }
        public string spde_observacion { get; set; }
        public bool spde_estado { get; set; }
        public string spde_auxv1 { get; set; }
        public string spde_auxv2 { get; set; }
        public Nullable<int> spde_auxi1 { get; set; }
        public Nullable<int> spde_auxi2 { get; set; }
    
        public virtual SoftCob_SPEECH_CABECERA SoftCob_SPEECH_CABECERA { get; set; }
    }
}
