//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_EMPLOYEE()
        {
            this.SoftCob_ESTUDIOS = new HashSet<SoftCob_ESTUDIOS>();
            this.SoftCob_EXPERIENCIA = new HashSet<SoftCob_EXPERIENCIA>();
            this.SoftCob_IDIOMAS = new HashSet<SoftCob_IDIOMAS>();
            this.SoftCob_OTROSESTUDIOS = new HashSet<SoftCob_OTROSESTUDIOS>();
            this.SoftCob_REFERENCIASLABORALES = new HashSet<SoftCob_REFERENCIASLABORALES>();
            this.SoftCob_REFERENCIASPERSONALES = new HashSet<SoftCob_REFERENCIASPERSONALES>();
        }
    
        public int EMPL_CODIGO { get; set; }
        public int DEPA_CODIGO { get; set; }
        public string empl_tipodocumento { get; set; }
        public string empl_identificacion { get; set; }
        public string empl_nombres { get; set; }
        public string empl_apellidos { get; set; }
        public System.DateTime empl_fechanacimiento { get; set; }
        public string empl_nacionalidad { get; set; }
        public string empl_genero { get; set; }
        public string empl_estadocivil { get; set; }
        public string emple_tiposangre { get; set; }
        public string empl_direccion { get; set; }
        public string empl_referencia { get; set; }
        public string empl_telefonocasa1 { get; set; }
        public string empl_telefonocasa2 { get; set; }
        public string empl_celular1 { get; set; }
        public string empl_celular2 { get; set; }
        public string empl_email1 { get; set; }
        public string empl_email2 { get; set; }
        public bool empl_estado { get; set; }
        public System.DateTime empl_fechacreacion { get; set; }
        public int empl_usuariocreacion { get; set; }
        public string empl_terminalcreacion { get; set; }
        public System.DateTime empl_fum { get; set; }
        public int empl_uum { get; set; }
        public string empl_tum { get; set; }
    
        public virtual SoftCob_DEPARTAMENTO SoftCob_DEPARTAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_ESTUDIOS> SoftCob_ESTUDIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_EXPERIENCIA> SoftCob_EXPERIENCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_IDIOMAS> SoftCob_IDIOMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_OTROSESTUDIOS> SoftCob_OTROSESTUDIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_REFERENCIASLABORALES> SoftCob_REFERENCIASLABORALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_REFERENCIASPERSONALES> SoftCob_REFERENCIASPERSONALES { get; set; }
    }
}
