//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_BITACORA_CAB
    {
        public int BICA_CODIGO { get; set; }
        public string bica_nombre { get; set; }
        public int bica_usucodigo { get; set; }
        public string bica_horalogueo { get; set; }
        public System.DateTime bica_fechabitacora { get; set; }
        public string bica_horabitacora { get; set; }
        public string bica_estado { get; set; }
        public string bica_auxv1 { get; set; }
        public string bica_auxv2 { get; set; }
        public string bica_auxv3 { get; set; }
        public string bica_auxv4 { get; set; }
        public string bica_auxv5 { get; set; }
        public Nullable<int> bica_auxi1 { get; set; }
        public Nullable<int> bica_auxi2 { get; set; }
        public Nullable<int> bica_auxi3 { get; set; }
        public Nullable<int> bica_auxi4 { get; set; }
        public Nullable<int> bica_auxi5 { get; set; }
        public System.DateTime bica_fechacreacion { get; set; }
        public int bica_usuariocreacion { get; set; }
        public string bica_terminalcreacion { get; set; }
        public System.DateTime bica_fum { get; set; }
        public int bica_uum { get; set; }
        public string bica_tum { get; set; }
    }
}
