//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_NOTAS_GESTION
    {
        public int NOTA_CODIGO { get; set; }
        public int nota_cedecodigo { get; set; }
        public int nota_cpcecodigo { get; set; }
        public int nota_perscodigo { get; set; }
        public int nota_gestor { get; set; }
        public string nota_descripcion { get; set; }
        public System.DateTime nota_revisarfecha { get; set; }
        public string nota_mantener { get; set; }
        public string nota_auxv1 { get; set; }
        public string nota_auxv2 { get; set; }
        public string nota_auxv3 { get; set; }
        public Nullable<int> nota_auxi1 { get; set; }
        public Nullable<int> nota_auxi2 { get; set; }
        public Nullable<int> nota_auxi3 { get; set; }
        public System.DateTime nota_fechacreacion { get; set; }
        public int nota_usuariocreacion { get; set; }
        public string nota_terminalcreacion { get; set; }
    }
}
