//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_PERSONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_PERSONA()
        {
            this.SoftCob_CLIENTE_DEUDOR = new HashSet<SoftCob_CLIENTE_DEUDOR>();
        }
    
        public int PERS_CODIGO { get; set; }
        public string pers_tipodocumento { get; set; }
        public string pers_numerodocumento { get; set; }
        public string pers_primernombre { get; set; }
        public string pers_segundonombre { get; set; }
        public string pers_primerapellido { get; set; }
        public string pers_segundoapellido { get; set; }
        public string pers_nombrescompletos { get; set; }
        public Nullable<System.DateTime> pers_fechanacimiento { get; set; }
        public string pers_genero { get; set; }
        public Nullable<int> pers_provincia { get; set; }
        public Nullable<int> pers_ciudad { get; set; }
        public string pers_estadocivil { get; set; }
        public string pers_direcciondomicilio { get; set; }
        public string pers_referenciadomicilio { get; set; }
        public string pers_direcciontrabajo { get; set; }
        public string pers_referenciatrabajo { get; set; }
        public bool pers_estado { get; set; }
        public string pers_auxv1 { get; set; }
        public string pers_auxiv2 { get; set; }
        public Nullable<int> pers_auxi1 { get; set; }
        public Nullable<int> pers_auxi2 { get; set; }
        public System.DateTime pers_fechacreacion { get; set; }
        public int pers_usuariocreacion { get; set; }
        public string pers_terminalcreacion { get; set; }
        public System.DateTime pers_fum { get; set; }
        public int pers_uum { get; set; }
        public string pers_tum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_CLIENTE_DEUDOR> SoftCob_CLIENTE_DEUDOR { get; set; }
    }
}
