//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_PROVINCIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_PROVINCIA()
        {
            this.SoftCob_CIUDAD = new HashSet<SoftCob_CIUDAD>();
        }
    
        public int PROV_CODIGO { get; set; }
        public int PAIS_CODIGO { get; set; }
        public int REGI_CODIGO { get; set; }
        public string prov_nombre { get; set; }
        public string prov_codigomarca { get; set; }
        public bool prov_estado { get; set; }
        public System.DateTime prov_fechacreacion { get; set; }
        public int prov_usuariocreacion { get; set; }
        public string prov_terminalcreacion { get; set; }
        public System.DateTime prov_fum { get; set; }
        public int prov_uum { get; set; }
        public string prov_tum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_CIUDAD> SoftCob_CIUDAD { get; set; }
    }
}
