//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_PERFIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_PERFIL()
        {
            this.SoftCob_PERFIL_MENU_TAREA = new HashSet<SoftCob_PERFIL_MENU_TAREA>();
            this.SoftCob_USUARIO = new HashSet<SoftCob_USUARIO>();
        }
    
        public int PERF_CODIGO { get; set; }
        public int empr_codigo { get; set; }
        public string perf_descripcion { get; set; }
        public string perf_observacion { get; set; }
        public Nullable<bool> perf_estado { get; set; }
        public Nullable<bool> perf_crearparametro { get; set; }
        public Nullable<bool> perf_modiparametro { get; set; }
        public Nullable<bool> perf_eliminaparametro { get; set; }
        public Nullable<bool> perf_perfilactitudinal { get; set; }
        public Nullable<bool> perf_estilosnegociacion { get; set; }
        public Nullable<bool> perf_metaprogramas { get; set; }
        public Nullable<bool> perf_modalidades { get; set; }
        public Nullable<bool> perf_estadosdelyo { get; set; }
        public Nullable<bool> perf_impulsores { get; set; }
        public Nullable<bool> perf_auxb1 { get; set; }
        public Nullable<bool> perf_auxb2 { get; set; }
        public Nullable<bool> perf_auxb3 { get; set; }
        public string perf_auxv1 { get; set; }
        public string perf_auxv2 { get; set; }
        public string perf_auxv3 { get; set; }
        public Nullable<int> perf_auxi1 { get; set; }
        public Nullable<int> perf_auxi2 { get; set; }
        public Nullable<int> perf_auxi3 { get; set; }
        public Nullable<System.DateTime> perf_fechacreacion { get; set; }
        public Nullable<int> perf_usuariocreacion { get; set; }
        public string perf_terminalcreacion { get; set; }
        public Nullable<System.DateTime> perf_fum { get; set; }
        public Nullable<int> perf_uum { get; set; }
        public string perf_tum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_PERFIL_MENU_TAREA> SoftCob_PERFIL_MENU_TAREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_USUARIO> SoftCob_USUARIO { get; set; }
    }
}
