//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_SEGMENTO_CABECERA
    {
        public int SGCA_CODIGO { get; set; }
        public int sgca_cedecodigo { get; set; }
        public int sgca_cpcecodigo { get; set; }
        public string sgca_segmento { get; set; }
        public string sgca_descripcion { get; set; }
        public int sgca_valorinicial { get; set; }
        public int sgca_valorfinal { get; set; }
        public bool sgca_estado { get; set; }
        public string sgca_auxv1 { get; set; }
        public string sgca_auxv2 { get; set; }
        public string sgca_auxv3 { get; set; }
        public Nullable<int> sgca_auxi1 { get; set; }
        public Nullable<int> sgca_auxi2 { get; set; }
        public Nullable<int> sgca_auxi3 { get; set; }
        public System.DateTime sgca_fechacreacion { get; set; }
        public int sgca_usuariocreacion { get; set; }
        public string sgca_terminalcreacion { get; set; }
        public System.DateTime sgca_fum { get; set; }
        public int sgca_uum { get; set; }
        public string sgca_tum { get; set; }
    }
}
