//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_PAGOSCABECERA
    {
        public int PCCA_CODIGO { get; set; }
        public int PACP_CODIGO { get; set; }
        public int pade_codigo { get; set; }
        public int pcca_cedecodigo { get; set; }
        public int pcca_cpcecodigo { get; set; }
        public string pcca_numerodocumento { get; set; }
        public string pcca_operacion { get; set; }
        public string pcca_auxv1 { get; set; }
        public string pcca_auxv2 { get; set; }
        public Nullable<int> pcca_auxi1 { get; set; }
        public Nullable<int> pcca_auxi2 { get; set; }
    
        public virtual SoftCob_PAGOSCARTERA SoftCob_PAGOSCARTERA { get; set; }
    }
}
