//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_GESTION_TELEFONICA
    {
        public int GETE_CODIGO { get; set; }
        public int gete_cedecodigo { get; set; }
        public int gete_cpcecodigo { get; set; }
        public int gete_ltcacodigo { get; set; }
        public int gete_ltdecodigo { get; set; }
        public int gete_cldecodigo { get; set; }
        public int gete_perscodigo { get; set; }
        public string gete_numerodocumento { get; set; }
        public string gete_operacion { get; set; }
        public int gete_gestorasignado { get; set; }
        public string gete_telefonogestionado { get; set; }
        public string gete_tipotelefono { get; set; }
        public string gete_propietario { get; set; }
        public int gete_araccodigo { get; set; }
        public int gete_arefcodigo { get; set; }
        public int gete_arrecodigo { get; set; }
        public int gete_arcocodigo { get; set; }
        public string gete_observacion { get; set; }
        public bool gete_efectivo { get; set; }
        public System.DateTime gete_fechagestion { get; set; }
        public System.TimeSpan gete_horagestion { get; set; }
        public string gete_tracknum { get; set; }
        public string gete_tiempogestion { get; set; }
        public string gete_tiempollamada { get; set; }
        public int gete_totalgestion { get; set; }
        public int gete_totalllamada { get; set; }
        public string gete_auxv1 { get; set; }
        public string gete_auxv2 { get; set; }
        public string gete_auxv3 { get; set; }
        public string gete_auxv4 { get; set; }
        public Nullable<int> gete_auxi1 { get; set; }
        public Nullable<int> gete_auxi2 { get; set; }
        public Nullable<int> gete_auxi3 { get; set; }
        public Nullable<int> gete_auxi4 { get; set; }
        public System.DateTime gete_fechacreacion { get; set; }
        public int gete_usuariocreacion { get; set; }
        public string gete_terminalcreacion { get; set; }
    }
}
