//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_ACCIONGESTION
    {
        public int ACCI_CODIGO { get; set; }
        public string acci_tipoaccion { get; set; }
        public int acci_idmotivo { get; set; }
        public string acci_observacion { get; set; }
        public int acci_codigocpce { get; set; }
        public string acci_identificacion { get; set; }
        public string acci_operacion { get; set; }
        public Nullable<int> acci_gestoranterior { get; set; }
        public Nullable<int> acci_gestoractual { get; set; }
        public string acci_datoanterior { get; set; }
        public string acci_auxv1 { get; set; }
        public string acci_auxv2 { get; set; }
        public string acci_auxv3 { get; set; }
        public Nullable<int> acci_auxi1 { get; set; }
        public Nullable<int> acci_auxi2 { get; set; }
        public Nullable<int> acci_auxi3 { get; set; }
        public System.DateTime acci_fechacreacion { get; set; }
        public int acci_usuariocreacion { get; set; }
        public string acci_terminalcreacion { get; set; }
    }
}
