//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_ESTRATEGIA_DETALLE
    {
        public int ESDE_CODIGO { get; set; }
        public int ESCA_CODIGO { get; set; }
        public int esde_caescodigo { get; set; }
        public string esde_operacion { get; set; }
        public string esde_valor { get; set; }
        public string esde_orden { get; set; }
        public int esde_prioridad { get; set; }
        public bool esde_estado { get; set; }
        public string esde_auxv1 { get; set; }
        public string esde_auxv2 { get; set; }
        public string esde_auxv3 { get; set; }
        public Nullable<int> esde_auxi1 { get; set; }
        public Nullable<int> esde_auxi2 { get; set; }
        public Nullable<int> esde_auxi3 { get; set; }
    
        public virtual SoftCob_ESTRATEGIA_CABECERA SoftCob_ESTRATEGIA_CABECERA { get; set; }
    }
}
