//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_CAMPOS_ESTRATEGIA
    {
        public int CAES_CODIGO { get; set; }
        public int TABD_CODIGO { get; set; }
        public string caes_nombre { get; set; }
        public string caes_tipo { get; set; }
        public bool caes_estado { get; set; }
        public string caes_auxv1 { get; set; }
        public string caes_auxv2 { get; set; }
        public string caes_auxv3 { get; set; }
        public Nullable<int> caes_auxi1 { get; set; }
        public Nullable<int> caes_auxi2 { get; set; }
        public Nullable<int> caes_auxi3 { get; set; }
        public System.DateTime caes_fechacreacion { get; set; }
        public int caes_usuariocreacion { get; set; }
        public string caes_terminalcreacion { get; set; }
        public System.DateTime caes_fum { get; set; }
        public int caes_uum { get; set; }
        public string caes_tum { get; set; }
    
        public virtual SoftCob_TABLAS_BDD SoftCob_TABLAS_BDD { get; set; }
    }
}
