//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_ESTRATEGIA_CABECERA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_ESTRATEGIA_CABECERA()
        {
            this.SoftCob_ESTRATEGIA_DETALLE = new HashSet<SoftCob_ESTRATEGIA_DETALLE>();
        }
    
        public int ESCA_CODIGO { get; set; }
        public string esca_estrategia { get; set; }
        public string esca_descripcion { get; set; }
        public bool esca_estado { get; set; }
        public string esca_auxv1 { get; set; }
        public string esca_auxv2 { get; set; }
        public string esca_auxv3 { get; set; }
        public Nullable<int> esca_auxi1 { get; set; }
        public Nullable<int> esca_auxi2 { get; set; }
        public Nullable<int> esca_auxi3 { get; set; }
        public System.DateTime esca_fechacreacion { get; set; }
        public int esca_usuariocreacion { get; set; }
        public string esca_terminalcreacion { get; set; }
        public System.DateTime esca_fum { get; set; }
        public int esca_uum { get; set; }
        public string esca_tum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_ESTRATEGIA_DETALLE> SoftCob_ESTRATEGIA_DETALLE { get; set; }
    }
}
