//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_GARANTES
    {
        public int GART_CODIGO { get; set; }
        public string gara_cedulatitular { get; set; }
        public string gara_cedulagarante { get; set; }
        public string gara_nombres { get; set; }
        public string gara_tipo { get; set; }
        public string gara_operacion { get; set; }
        public string gara_auxv1 { get; set; }
        public string gara_auxv2 { get; set; }
        public string gara_auxv3 { get; set; }
        public string gara_auxv4 { get; set; }
        public string gara_auxv5 { get; set; }
        public Nullable<int> gara_auxi1 { get; set; }
        public Nullable<int> gara_auxi2 { get; set; }
        public Nullable<int> gara_auxi3 { get; set; }
        public Nullable<int> gara_auxi4 { get; set; }
        public Nullable<int> gara_auxi5 { get; set; }
        public System.DateTime gara_fechacreacion { get; set; }
        public int gara_usuariocreacion { get; set; }
        public string gara_terminalcreacion { get; set; }
        public System.DateTime gara_fum { get; set; }
        public int gara_uum { get; set; }
        public string gara_tum { get; set; }
    }
}
