//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_PAGOSCARTERA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_PAGOSCARTERA()
        {
            this.SoftCob_PAGOSCABECERA = new HashSet<SoftCob_PAGOSCABECERA>();
        }
    
        public int PACP_CODIGO { get; set; }
        public int pade_codigo { get; set; }
        public int pacp_cedecodigo { get; set; }
        public int pacp_cpcecodigo { get; set; }
        public string pacp_numerodocumento { get; set; }
        public string pacp_operacion { get; set; }
        public string pacp_documento { get; set; }
        public System.DateTime pacp_fechapago { get; set; }
        public decimal pacp_valorpago { get; set; }
        public Nullable<int> pacp_gestor { get; set; }
        public Nullable<int> pacp_diasmora { get; set; }
        public string pacp_rangodias { get; set; }
        public string pacp_auxv1 { get; set; }
        public string pacp_auxv2 { get; set; }
        public Nullable<int> pacp_auxi1 { get; set; }
        public Nullable<int> pacp_auxi2 { get; set; }
        public System.DateTime pacp_fechacreacion { get; set; }
        public int pacp_usuariocreacion { get; set; }
        public string pacp_terminalcreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_PAGOSCABECERA> SoftCob_PAGOSCABECERA { get; set; }
    }
}
