//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_CITACIONES_CAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_CITACIONES_CAB()
        {
            this.SoftCob_CITACIONES_DET = new HashSet<SoftCob_CITACIONES_DET>();
        }
    
        public int CITA_CODIGO { get; set; }
        public int CLDE_CODIGO { get; set; }
        public int pers_codigo { get; set; }
        public string cita_estado { get; set; }
        public System.DateTime cita_fechacitacion { get; set; }
        public int chor_codigo { get; set; }
        public decimal cita_valorcitacion { get; set; }
        public int cita_usuacitacion { get; set; }
        public int cita_numerocitacion { get; set; }
        public string cita_observacioncitacion { get; set; }
        public string cita_tipoconvenio { get; set; }
        public string cita_observacionconvenio { get; set; }
        public Nullable<System.DateTime> cita_fechaconvenio { get; set; }
        public Nullable<decimal> cita_totalconvenio { get; set; }
        public Nullable<decimal> cita_cuotas { get; set; }
        public Nullable<int> cita_numcuotas { get; set; }
        public string cita_numjuicio { get; set; }
        public Nullable<int> cita_plazo { get; set; }
        public Nullable<bool> cita_terreno { get; set; }
        public string cita_direccion { get; set; }
        public string cita_referencia { get; set; }
        public Nullable<bool> cita_whatsapp { get; set; }
        public string cita_celular { get; set; }
        public Nullable<bool> cita_email { get; set; }
        public string cita_correo { get; set; }
        public byte[] cita_citacion { get; set; }
        public string cita_pathcitacion { get; set; }
        public string cita_nomcitacion { get; set; }
        public string cita_extcitacion { get; set; }
        public string cita_contentcitacion { get; set; }
        public byte[] cita_convenio { get; set; }
        public string cita_pathconvenio { get; set; }
        public string cita_nomconvenio { get; set; }
        public string cita_extconvenio { get; set; }
        public string cita_contentconvenio { get; set; }
        public byte[] cita_identificacion { get; set; }
        public string cita_pathidentifica { get; set; }
        public string cita_nomidentifica { get; set; }
        public string cita_extidentifica { get; set; }
        public string cita_contentidentifica { get; set; }
        public byte[] cita_pagare { get; set; }
        public string cita_pathpagare { get; set; }
        public string cita_nompagare { get; set; }
        public string cita_extpagare { get; set; }
        public string cita_contentpagare { get; set; }
        public string cita_auxv1 { get; set; }
        public string cita_auxv2 { get; set; }
        public string cita_auxv3 { get; set; }
        public string cita_auxv4 { get; set; }
        public string cita_auxv5 { get; set; }
        public string cita_auxv6 { get; set; }
        public string cita_auxv7 { get; set; }
        public string cita_auxv8 { get; set; }
        public string cita_auxv9 { get; set; }
        public string cita_auxv10 { get; set; }
        public Nullable<int> cita_auxi1 { get; set; }
        public Nullable<int> cita_auxi2 { get; set; }
        public Nullable<int> cita_auxi3 { get; set; }
        public Nullable<int> cita_auxi4 { get; set; }
        public Nullable<int> cita_auxi5 { get; set; }
        public Nullable<System.DateTime> cita_auxf1 { get; set; }
        public Nullable<System.DateTime> cita_auxf2 { get; set; }
        public Nullable<System.DateTime> cita_auxf3 { get; set; }
        public Nullable<decimal> cita_auxd1 { get; set; }
        public Nullable<decimal> cita_auxd2 { get; set; }
        public Nullable<decimal> cita_auxd3 { get; set; }
        public System.DateTime cita_fechacreacion { get; set; }
        public int cita_usuariocreacion { get; set; }
        public string cita_terminalcreacion { get; set; }
        public System.DateTime cita_fum { get; set; }
        public int cita_uum { get; set; }
        public string cita_tum { get; set; }
    
        public virtual SoftCob_CLIENTE_DEUDOR SoftCob_CLIENTE_DEUDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_CITACIONES_DET> SoftCob_CITACIONES_DET { get; set; }
    }
}
