//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_ARBOL_SCORETELEFONO
    {
        public int ARST_CODIGO { get; set; }
        public int arst_cedecodigo { get; set; }
        public int arst_cpcecodigo { get; set; }
        public int arst_araccodigo { get; set; }
        public int arst_arefcodigo { get; set; }
        public int arst_arrecodigo { get; set; }
        public int arst_arcocodigo { get; set; }
        public string arst_califica { get; set; }
        public int arst_cantidad { get; set; }
        public int arst_valor { get; set; }
        public bool arst_estado { get; set; }
        public string arst_auxv1 { get; set; }
        public string arst_auxv2 { get; set; }
        public Nullable<int> arst_auxi1 { get; set; }
        public Nullable<int> arst_auxi2 { get; set; }
        public System.DateTime arst_fechacreacion { get; set; }
        public int arst_usuariocreacion { get; set; }
        public string arst_terminalcreacion { get; set; }
        public System.DateTime arst_fum { get; set; }
        public int arst_uum { get; set; }
        public string arst_tum { get; set; }
    }
}
