//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_MENU_TAREA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftCob_MENU_TAREA()
        {
            this.SoftCob_PERFIL_MENU_TAREA = new HashSet<SoftCob_PERFIL_MENU_TAREA>();
        }
    
        public int META_CODIGO { get; set; }
        public int MENU_CODIGO { get; set; }
        public int TARE_CODIGO { get; set; }
        public int empr_codigo { get; set; }
        public bool meta_estado { get; set; }
        public int meta_orden { get; set; }
        public string meta_auxv1 { get; set; }
        public string meta_auxv2 { get; set; }
        public string meta_auxv3 { get; set; }
        public Nullable<int> meta_auxi1 { get; set; }
        public Nullable<int> meta_auxi2 { get; set; }
        public Nullable<int> meta_auxi3 { get; set; }
        public System.DateTime meta_fechacreacion { get; set; }
        public int meta_usuariocreacion { get; set; }
        public string meta_terminalcreacion { get; set; }
        public System.DateTime meta_fum { get; set; }
        public int meta_uum { get; set; }
        public string meta_tum { get; set; }
    
        public virtual SoftCob_MENU SoftCob_MENU { get; set; }
        public virtual SoftCob_TAREA SoftCob_TAREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftCob_PERFIL_MENU_TAREA> SoftCob_PERFIL_MENU_TAREA { get; set; }
    }
}
