//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSoftCob
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftCob_REFERENCIASLABORALES
    {
        public int RELA_CODIGO { get; set; }
        public int EMPL_CODIGO { get; set; }
        public string rela_nombre { get; set; }
        public string rela_empresa { get; set; }
        public string rela_cargo { get; set; }
        public string rela_telefono { get; set; }
        public string rela_celular { get; set; }
        public string rela_email { get; set; }
    
        public virtual SoftCob_EMPLOYEE SoftCob_EMPLOYEE { get; set; }
    }
}
